#!/usr/bin/env python3.3
import urllib.request
import urllib.parse
import json, os
# from PyQt import QtCore, QtGui

TEMP_FILE = r"C:\project\pyton\http\temp.txt"

# url = 'http://eu.battle.net/api/wow/character/' + urllib.parse.quote(u'Голдринн') + urllib.parse.quote(u'/Нейвар') + '?fields=stats'
# f = urllib.request.urlopen(url)
# result = f.read().decode('utf-8')
# a = json.loads(result)

if os.path.isfile(TEMP_FILE):
  file = open(TEMP_FILE, mode='r')
  fileName = file.read()
	file.close()
else:
	auc = 'http://eu.battle.net/api/wow/auction/data/' + urllib.parse.quote(u'Голдринн')
	f = urllib.request.urlopen(auc)
	result = eval(f.read().decode('utf-8'))
	fileName = result["files"][0]["url"]

	file = open(TEMP_FILE, mode='w')
	file.write(fileName)
	file.close()

class Auction(object):
	def __init(self):
		self.__dump = []

	def addDump(self, dump):
		self.__dump = dump["alliance"]['auctions']

	def a(self):
		return self.__dump[0]

	def getBidsByName(self, name):
		return filter(lambda x, y = name: x["owner"]==y, self.__dump)
	def getItemById(self, itemId):
		url = 'http://eu.battle.net/api/wow/item/' + urllib.parse.quote(u'%s'%itemId)
		f = urllib.request.urlopen(url)
		return json.loads(f.read().decode('utf-8'))["name"]

f = urllib.request.urlopen(fileName)
print("scanning")
# result = eval(f.read().decode('utf-8'))["realm"]

auction = Auction()
auction.addDump(json.loads(f.read().decode('utf-8')))
items = map(lambda x: auction.getItemById(x["item"]), auction.getBidsByName('Нейвар'))
print(list(items))
